# Generated by Django 2.2 on 2020-04-25 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200324_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='quantity',
        ),
    ]
